### ISSUE TITLE
Posix baud rates are missing some values

### ISSUE THREAD

**Issue by truedat101** [NCrashed/serial-port#10]
Hunting around for the current baud rates, I'm guessing these might be depending on what version of standards are being used.

Looking here: http://linux.die.net/man/3/termios

```
B0

B50

B75

B110

B134

B150

B200

B300

B600

B1200

B1800

B2400

B4800

B9600

B19200

B38400

B57600

B115200 
```

**Comment by NCrashed** [comment]
Implemented in #12
