### ISSUE TITLE
compiler error with the latest dmd compiler

### ISSUE THREAD

**Issue by gedaiu** [NCrashed/serial-port#13]
```
../../.dub/packages/serial-port-1.1.0/source/serial/device.d(985,56): Error: undefined identifier 'speed_t', did you mean function 'speed'?
../../.dub/packages/serial-port-1.1.0/source/serial/device.d(1002,21): Error: undefined identifier 'speed_t', did you mean function 'speed'?
../../.dub/packages/serial-port-1.1.0/source/serial/device.d(1035,18): Error: undefined identifier 'termios'
```

**Comment by NCrashed** [comment]
Which compiler version you have tried with?

**Comment by gedaiu** [comment]
it's dmd 2.070 on osx 


```
➜  ~  dmd --version
DMD64 D Compiler v2.070.0
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright
```

**Comment by o3o** [comment]
For me works.

My release:
```
$ cd serial-port
$ git describe --tags
v1.1.0-9-gf7d5314
```

and my dmd version
```
$ dmd --version
DMD64 D Compiler v2.070
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright
```

**Comment by NCrashed** [comment]
Seems there is problem in phobos headers for osx. Linux dmd 2.070 compiles well. I don't have mac, but I'll see what I can do.

**Comment by aaronhyperum** [comment]
While testing, I encountered the same problem as the OP. Same system as well.

**Comment by aaronhyperum** [comment]
Hey, NCrashed, I did some digging and it seems the dub version of this repo is not up to date. For example, it doesn't include `import core.sys.posix.termios;` nor does it have `version(OSX)` in it. Do you know why? (dub.json uses version "~master" of the repo.)

**Comment by NCrashed** [comment]
A new release published and `README.md` is updated to recommend usage of `~>1.2` notation instead of branch notation.
