### ISSUE TITLE
Linux GDC compile fails with undefined identifier

### ISSUE THREAD

**Issue by truedat101** [NCrashed/serial-port#8]
Building serial-port 1.1.0+commit.4.gf036724 configuration "library", build type debug.
Running gdc...
source/serial/device.d:1014: error: undefined identifier B57600, did you mean variable B576000?
source/serial/device.d:1092: error: undefined identifier B57600, did you mean variable B576000?

Looking at the source, it seems the mac os x platform definition does the right thing.  Do that for Linux.

**Comment by NCrashed** [comment]
`core.sys.linux.termios` module for GDC misses definition for `B57600`, some frontend lag between DMD and GDC. I'm going to add version clause for GDC.
